[versions]
#Android
gradle = "8.7.3"
#Kotlin
kotlin = "2.0.21"
#Ksp
devtoolsKsp = "2.0.21-1.0.27"
#Hilt
hiltAndroid = "2.52"
#Libraries
composeBom = "2024.12.01"
compose = "1.5.15"
navigationCompose = "2.8.5"
hiltNavigationCompose = "1.2.0"
room = "2.6.1"
serialization = "1.7.3"
#Tests
runner = "1.6.2"
uiTestJunit4 = "1.7.6"
kotlinxCoroutinesTest = "1.9.0"
truth = "1.1.3"
uiTestManifest = "1.7.6"
material3Android = "1.3.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
#Tests
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationCompose" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroid" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }